#+title: La música y la lucha de clases

La cultura es la representación física de las relaciones, procesos y fenómenos sociales históricos de una sociedad. Es, por esta razón, "útil". La música, por supuesto, no es la excepción. Uno puede pensar en alguna canción cualquiera que pareciese inútil o que haga alusión a relaciones sociales que nos puedan parecer despreciables y pensar que, o se trata de una excepción (música que no es música), o estamos ante un enriquecimiento de la cultura (música que no es mala, sino que es de un género diferente). Estos dos caminos son los fundamentos de la crítica de la cultura y de la música en general y nos llevan a interesantes y muy elaboradas conclusiones. Sin embargo, con animo de resolver el problema del papel y la naturaleza general de la cultura, empezaremos por explicar y desmentir esta concepción errada de la cultura.

Piense en alguna canción popular que le parezca despreciable. Puede ser sonora o líricamente buena o mala, a su juicio y al juicio de los artistas y la prensa. Sin embargo, lo que nos importa es el juicio del estudio de la cultura. En este juicio no existe la buena o la mala música, en realidad, la música, como decíamos al principio respecto a la cultura, representa los fenómenos de una sociedad particular. De esta manera, a partir de su representación, somos capaces de hacer un juicio, quizás apresurado, quizás superficial, pero seriamos capaces de armar un juicio, sobre el estado general de la sociedad.

En las protestas populares la música juega un papel muy importante. Sirve para propagar ideas precisas del motor del movimiento social que se está formando. Hay que tener en cuenta que los movimientos, así como los fenómenos sociales en general, están compuestos por personas. Son las personas, el conjunto de personas, la forma en la que se relacionan, es decir, las relaciones sociales, las que componen los movimientos sociales. De manera que la música de un movimiento social es tanto el medio para propagar ideas particulares que sirven como catalizador de los individuos dispersos en un solo grupo, como también toma la forma objetiva de su papel en la historia. Canciones de protesta como la canción española A las barricadas, que deriva de otra canción rusa, La Varsoviana, ponen de manifiesto a los oyentes
